config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ルートパス(TOPページ)
  root 'homes#top'

  # ユーザールーティング
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'withdrawal' => 'users#withdrawal_show'
      patch 'withdrawal'
      get 'post'
      get 'like'
    end
  end
  resources :posts do
    member do
      get 'like'
    end
    collection do
      get 'ranking'
      get 'comment'
    end
    resources :post_comments, only: [:create, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get '/search' => 'searchs#search', as: 'search'
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  # 他モデルとの関連付け
  belongs_to :user
  belongs_to :post

  # バリデーション
  validates :comment, presence: true

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  # ログインユーザのみアクセス許可
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.post_id = @post.id
    # APIにリクエスト送信
    @comment.score = Language.get_data(post_comment_params[:comment])
    if @comment.save
      @comment = PostComment.new
      flash.now[:notice] = "コメントを投稿しました"
    else
      render '/posts/show'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = PostComment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = PostComment.find(params[:id])
    if @comment.update(post_comment_params)
      flash[:notice] = "コメントを更新しました"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = PostComment.find_by(id: params[:id], post_id: @post.id)
    if @comment.destroy
      @comment = PostComment.new
      flash.now[:notice] = "コメントを削除しました"
    end
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/post_comment_helper.rb
module PostCommentHelper
end

app/views/post_comments/_post_comment_new.html.erb
<% if flash[:notice] %>
  <p class="alert alert-info mt-3 comment-flash"><%= flash[:notice] %></p>
<% end %>

<div class="mt-3 mb-5">
  <%= form_with(model:[post, comment], url: post_post_comments_path(post.id), method: :post, remote: true, data: {"turbolinks" => false}) do |f| %>
    <%= f.text_area :comment, class:"col-10 form-control", placeholder: "コメントを入力してください" %>
    <%= f.submit '投稿', class:"col-1 btn btn-info form-control" %>
  <% end %>
</div>


<!--コメント数が0じゃなかったらコメントを一覧表示する-->
  <% if post.post_comments.count != 0 %>

    <div class="row comment-index mb-5">
      <% post.post_comments.each do |comment| %>
        <!--コメント一覧表示-->
        <div class="col-2">
          <%= link_to user_path(comment.user.name) do %>
            <%= comment.user.name %>さん
          <% end %>
        </div>
        <div class="col-2">
          <%= comment.updated_at.strftime("%Y-%m-%d %H:%M") %>
        </div>
        <div class="col-6">
          <%= comment.comment %>
        </div>
        <div class="col-1">
          <div class="score text-center">
            <%= comment.score %>
          </div>
        </div>

      <!--コメント投稿者のみ編集・削除ボタン表示-->
      <% if comment.user_id == current_user.id %>
        <div class="col-1">
          <%= link_to edit_post_post_comment_path(post.id, comment.id), method: :get do %>
            <i class="fas fa-edit"></i>
          <% end %>

          <%= link_to post_post_comment_path(post.id, comment.id), method: :delete, remote: true, data: {"turbolinks" => false}, "data-confirm" => "本当に削除しますか？" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      <% else %>
        <div class="col-1"></div>
        <div class="col-1"></div>
      <% end %>

  <% end %>

  <% else %>
    <!--コメント数が0だったら表示-->
    <div class="no-message-box">
      <p class="text-center">コメントはありません</p>
    </div>

  <% end %>

app/views/post_comments/create.js.erb
$(".comment_new_btn").html("<%= j(render partial: 'post_comments/post_comment_new', locals: {post: @post, comment: @comment}) %>");

app/views/post_comments/destroy.js.erb
$(".comment_new_btn").html("<%= j(render partial: 'post_comments/post_comment_new', locals: {post: @post, comment: @comment }) %>");

app/views/post_comments/edit.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/errors', obj: @comment %>

<div class="container">
  <div class="row justify-content-start login">
    <div class="col-6">
    <h2>コメント編集</h2>
    </div>
  </div>

  <!--編集フォーム-->
  <div class="comment">
    <%= form_with(model:[@post, @comment], url: post_post_comment_path(@post.id), method: :patch, local: true) do |f| %>
      <%= f.text_area :comment, class:"col-10 form-control", placeholder: "コメントを入力してください" %>
      <%= f.submit '更新', class:"col-1 btn btn-info form-control" %>
    <% end %>
  </div>

  <%= link_to '戻る', post_path(@post.id), method: :get %>

</div>