config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ルートパス(TOPページ)
  root 'homes#top'

  # ユーザールーティング
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'withdrawal' => 'users#withdrawal_show'
      patch 'withdrawal'
      get 'post'
      get 'like'
    end
  end
  resources :posts do
    member do
      get 'like'
    end
    collection do
      get 'ranking'
      get 'comment'
    end
    resources :post_comments, only: [:create, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get '/search' => 'searchs#search', as: 'search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 他モデルとの関連付け
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  # バリデーション
  validates :name, presence: true
  validates :gender, presence: true
  validates :age, presence: true
  validates :email, presence: true

  # 性別をenumで管理
  enum gender: { '男性': 0, '女性': 1, 'その他': 2 }

  # 年齢をenumで管理
  enum age: { '10代': 0, '20代': 1, '30代': 2, '40代': 3, '50代': 4, '60代': 5, '70歳以上': 6 }

  # ログインするときに退会済のユーザーを弾く
  def active_for_authentication?
    super && (is_dleted == false)
  end

  # ゲストログインのアカウント
  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@guest.com', gender: 0, age: 0) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age])
  end

  def after_sign_up_path_for(resource)
    posts_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest
    user = User.guest
    if sign_in user
      flash[:notice] = "ゲストユーザーとしてログインしました"
      redirect_to posts_path
    else
      render 'new_guest'
    end
  end

  def after_sign_in_path_for(resource)
    posts_path
  end

  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:notice] = "退会済みのユーザーです"
        redirect_to new_user_session_path
      end
    else
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ログインユーザのみアクセス許可
  before_action :authenticate_user!
  # ゲストログイン情報の編集不可
  before_action :check_guest, only: [:update, :withdrawal]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を変更しました"
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def post
    @user = User.find(params[:id])
    @users = Kaminari.paginate_array(@user.posts).page(params[:page]).per(20)
  end

  def like
    @user = User.find(params[:id])
    @users = Kaminari.paginate_array(@user.favorite_posts).page(params[:page]).per(10)
  end

  def withdrawal
    @user = User.find(params[:id])
    if @user.update(is_dleted: true)
      reset_session
      flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
      redirect_to root_path
    end
  end

  def check_guest
    if current_user.email == 'guest@guest.com'
      flash[:notice] = "ゲストユーザーは変更・退会できません"
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :gender, :age, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/errors', obj: @user %>

<div class="container">

  <div class="row justify-content-center login">
    <div class="col-6">
      <h2>会員登録</h2>
    </div>
  </div>

  <%= form_with model: @user, url: user_path(@user), method: :patch, local: true do |f| %>

    <div class="row form-group justify-content-center">
      <label class="col-2">ニックネーム</label>
      <div class="col-3">
        <%= f.text_field :name, class: "form-control", autofocus: true, autocomplete: "name" %>
      </div>
    </div>

    <div class="row form-group justify-content-center">
      <label class="col-2">性別</label>
      <div class="col-3">
        <%= f.select :gender, User.genders.keys, { prompt: "選択してください"}, { class: "form-control" } %>
      </div>
    </div>

    <div class="row form-group justify-content-center">
      <label class="col-2">年齢</label>
      <div class="col-3">
        <%= f.select :age, User.ages.keys, { prompt: "選択してください"}, { class: "form-control" } %>
      </div>
    </div>

    <div class="row form-group justify-content-center">
      <label class="col-2">メールアドレス</label>
      <div class="col-3">
        <%= f.email_field :email, class: "form-control", autocomplete: "email" %>
      </div>
    </div>

    <div class="row form-group justify-content-center">
      <div class="col-2">
        <%= f.submit "変更", class: "btn btn-info btn-lg" %>
      </div>
    </div>

    <div class="row form-group justify-content-center">
      <div class="col-6">
        <%= link_to '戻る', user_path(@user) %>
      </div>
    </div>

  <% end %>
</div>

app/views/users/like.html.erb
<div class="container">

  <div class="row justify-content-center login">
    <div class="col-6">
      <h2><%= @user.name %>さんがいいねした投稿</h2>
    </div>
  </div>

  <% if @users.count != 0 %>

    <!--いいねした投稿があれば一覧を表示する-->
    <% @users.each do |post| %>
      <!--投稿表示部分-->
      <div class="row">
        <div class="post">
          <%= render 'posts/item', post: post %>
          <div class="sub">
            <%= render 'posts/time', post: post %>
            <%= render partial: 'posts/favorite', locals: {post: post} %>
            <%= render 'posts/comment', post: post %>
          </div>
        </div>
      </div>
    <% end %>

  <% else %>
    <!--いいねした投稿がなければ表示-->
    <div class="no-message-box">
     <p class="text-center">まだありません</p>
    </div>

  <% end %>

  <!--ページネーション-->
  <%= render 'layouts/pager', obj: @users %>

</div>

app/views/users/post.html.erb
<div class="container">

  <div class="row justify-content-center login">
    <div class="col-6">
      <h2><%= @user.name %>さんの投稿一覧</h2>
    </div>
  </div>

  <% if @users.count != 0 %>

    <!--ユーザの投稿があれば一覧表示する-->
    <% @users.each do |post| %>
      <!--投稿表示部分-->
      <div class="row">
        <div class="post">
          <%= render 'posts/item', post: post %>
          <div class="sub">
            <%= render 'posts/time', post: post %>
            <%= render partial: 'posts/favorite', locals: {post: post} %>
            <%= render 'posts/comment', post: post %>
          </div>
        </div>
      </div>
    <% end %>
  
  <% else %>
    <!--投稿がなければ表示-->
    <div class="no-message-box">
     <p class="text-center">投稿はありません</p>
    </div>

  <% end %>

  <!--ページネーション-->
  <%= render 'layouts/pager', obj: @users %>

</div>

app/views/users/show.html.erb
<!--サクセスメッセージ-->
<%= render 'layouts/success' %>

<div class="container">

  <div class="row justify-content-center login">
    <div class="col-6">
      <h2><%= @user.name %>さんのページ</h2>
    </div>
  </div>

  <div class="row justify-content-center">
    <label class="col-2">ニックネーム</label>
    <div class="col-4"><%= @user.name %></div>
  </div>

  <div class="row justify-content-center">
    <label class="col-2">性別</label>
    <div class="col-4"><%= @user.gender %></div>
  </div>

  <div class="row justify-content-center">
    <label class="col-2">年齢</label>
    <div class="col-4"><%= @user.age %></div>
  </div>

  <!--個人情報表示、編集、退会はログインユーザーのみ表示-->
  <% if current_user.id == @user.id %>
    <div class="row justify-content-center">
      <label class="col-2">メールアドレス</label>
      <div class="col-4"><%= @user.email %></div>
    </div>

    <div class="row justify-content-center">
      <%= link_to '編集', edit_user_path(@user.id), class: "btn btn-info col-1" %>
    </div>
  <% end %>

  <div class="row justify-content-center mt-5">
    <label class="col-2">総投稿数</label>
    <div class="col-4">
      <%= link_to post_user_path(@user.id) do %>
        <%= @user.posts.count %>句
      <% end %>
    </div>
  </div>

  <% if current_user.id == @user.id %>
    <div class="row justify-content-center">
      <label class="col-2">いいねした投稿</label>
      <%= link_to '一覧を見る', like_user_path(@user.id), class: "col-4" %>
    </div>

    <div class="row justify-content-end mt-5">
      <%= link_to '退会する', withdrawal_user_path(@user.id), method: :get, class: "btn btn-secondary btn-sm col-1" %>
    </div>

  <% end %>




</div>

app/views/users/withdrawal_show.html.erb
<div class="container">

  <div class="message" >
    本当に退会しますか？</br>
    退会すると、今までのデータは全て消去されます。
  </div>

  <div class="row justify-content-center align-items-start mt-5">
    <%= link_to '戻る', user_path(current_user), method: :get, class: "btn btn-info btn-lg col-3 mr-3" %>
    <%= link_to '退会する', withdrawal_user_path(current_user), method: :patch, class: "btn btn-secondary btn-sm col-1" %>
  </div>

</div>