config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ルートパス(TOPページ)
  root 'homes#top'

  # ユーザールーティング
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'withdrawal' => 'users#withdrawal_show'
      patch 'withdrawal'
      get 'post'
      get 'like'
    end
  end
  resources :posts do
    member do
      get 'like'
    end
    collection do
      get 'ranking'
      get 'comment'
    end
    resources :post_comments, only: [:create, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get '/search' => 'searchs#search', as: 'search'
end

app/models/post.rb
class Post < ApplicationRecord
  # 他モデルとの関連付け
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  # バリデーション
  validates :theme, presence: true
  validates :text, presence: true

  # 投稿に対していいねが存在しているか
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # ログインユーザのみアクセス許可
  before_action :authenticate_user!

  def index
    @posts = Post.all.order(updated_at: "DESC").page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿が完了しました"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = PostComment.new
    @score = @post.post_comments.average(:score)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿内容を更新しました"
      redirect_to post_path(@post.id)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "投稿を削除しました"
      redirect_to posts_path
    end
  end

  def like
    @post = Post.find(params[:id])
    @post = Kaminari.paginate_array(@post.favorited_users).page(params[:page]).per(20)
  end

  def ranking
    # 日付を変数にいれる
    today = Date.today
    yesterday = today.ago(1.days)
    day_before_yesterday = today.ago(2.days)
    # それぞれの投稿日のいいね数が一番のものを取り出す
    @today = Post.find(Favorite.includes(:post).where(posts: { created_at: today.beginning_of_day..today.end_of_day }).group(:post_id).order('count(post_id) desc').limit(1).pluck(:post_id))
    @yesterday = Post.find(Favorite.includes(:post).where(posts: { created_at: yesterday.beginning_of_day..yesterday.end_of_day }).group(:post_id).order('count(post_id) desc').limit(1).pluck(:post_id))
    @day_before_yesterday = Post.find(Favorite.includes(:post).where(posts: { created_at: day_before_yesterday.beginning_of_day..day_before_yesterday.end_of_day }).group(:post_id).order('count(post_id) desc').limit(1).pluck(:post_id))
  end

  def comment
    # コメントステータスがtrue（募集の投稿）を取り出す
    # 最終編集瓶から２日たっているものは表示しないようにする（ステータスの切替はしない
    date = Date.today - 2
    @posts = Post.where(comment_status: true).where("updated_at >= '#{date}'").order(created_at: "DESC")
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(10)
  end

  private

  def post_params
    params.require(:post).permit(:theme, :text, :comment_status)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<!--コメントボタン、件数表示-->
<i class="far fa-comment-alt"></i>&nbsp;
<%= link_to post_path(post.id) do %>
  <%= post.post_comments.count %>
<% end %>

app/views/posts/_favorite.html.erb
<!--いいねボタン、件数表示-->
<div class="favorite_btn_<%= post.id %>">
  <% if post.favorited_by?(current_user) %>
    <!--投稿に対してユーザーがイイねしている場合-->
    <%= link_to post_favorites_path(post), method: :delete, remote: true, data: {"turbolinks" => false} do %>
      <i class="fas fa-heart" aria-hidden="true" style="color: red"></i>&nbsp;
    <% end %>
  <% else %>
    <!--投稿に対してユーザーがイイねしていない場合-->
    <%= link_to post_favorites_path(post), method: :post, remote: true, data: {"turbolinks" => false} do %>
      <i class="far fa-heart" aria-hidden="true"></i>&nbsp;
    <% end %>
  <% end %>

  <%= link_to like_post_path(post.id) do %>
    <%= post.favorites.count %></br>
  <% end %>
</div>

app/views/posts/_item.html.erb
<!--お題、川柳を表示部分-->
<div class="main">
  <div class="box">
    <p class="theme">お題 「<%= post.theme %>」</p>
    <div class="text">
      <%= post.text %>
    </div>
  </div>
</div>

app/views/posts/_language.html.erb
<!--スコアの平均点表示-->
<p class="comment-score">コメントの感情分析スコア</p>
<div class="score text-center">
  <%= @score %>
</div>

app/views/posts/_post.html.erb
<!--新規投稿フォーム-->

<div class="row form-group justify-content-center mt-5">
  <label class="col-offset-2 col-3">お題</label>
  <%= f.text_field :theme, class:"col-4 form-control" %>
</div>

<div class="row form-group justify-content-center">
  <label class="col-3">本文</label>
  <%= f.text_area :text, class:"col-4 form-control" %>
</div>

<div class="row form-group justify-content-center">
  <label class="col-3">コメントを募集しますか？</label>
  <div class="col-6">
    <%= f.radio_button :comment_status, 'true' %>はい
    <%= f.radio_button :comment_status, 'false', checked: true %>いいえ</br>
    <p>はいを選択をすると、コメント募集ページに二日間投稿がのります。</p>
  </div>
</div>

app/views/posts/_time.html.erb
<!--投稿ユーザー名、投稿時間表示部分-->
<div class="time">
<%= link_to user_path(post.user) do %>
          <%= post.user.name %></br>
        <% end %>
        <%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></br>

</div>

app/views/posts/comment.html.erb
<div class="container" >

  <div class="cmment_status">
    <p class="ranking-message">投稿時に「コメントを募集しますか？」で「はい」を選択した投稿が二日間表示されます。</br>
    たくさんのコメントお待ちしております！</p>
  </div>

  <!--投稿表示部分-->
  <% @posts.each do |post| %>
    <div class="row">
      <div class="post">
        <%= render 'posts/item', post: post %>
        <div class="sub">
          <%= render 'posts/time', post: post %>
          <%= render partial: 'posts/favorite', locals: {post: post} %>
          <%= render 'posts/comment', post: post %>
        </div>
      </div>
    </div>
  <% end %>

  <!--ページネーション-->
  <%= render 'layouts/pager', obj: @posts %>

</div>

app/views/posts/edit.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/errors', obj: @post %>

<div class="container">

  <h2 class="post-title">投稿編集</h2>

  <%= form_with model: @post, url: post_path, method: :patch, local: true do |f| %>
    <!--編集フォーム-->
    <%= render 'posts/post', f: f %>
    <div class="row form-group justify-content-center">
      <%= f.submit '更新する', class: "col-2 btn btn-info btn-lg" %>
    </div>
  <% end %>

  <div class="row">
    <%=link_to '戻る', post_path(@post), class: "col-1" %>
  </div>

</div>

app/views/posts/index.html.erb
<!--サクセスメッセージ-->
<%= render 'layouts/success' %>

<div class="container" >
 <% @posts.each do |post| %>
    <!--投稿表示-->
    <div class="row">
      <div class="post">
        <%= render 'posts/item', post: post %>
        <div class="sub">
          <%= render 'posts/time', post: post %>
          <%= render partial: 'posts/favorite', locals: {post: post} %>
          <%= render 'posts/comment', post: post %>
        </div>
      </div>
    </div>
 <% end %>

  <!--ぺージネーション-->
  <%= render 'layouts/pager', obj: @posts %>
</div>

app/views/posts/like.html.erb
<div class="container">

  <div class="post-title">
    <h2>この投稿にいいねしたユーザー</h2>
  </div>

  <% if @post.count != 0 %>
    <% @post.each do |user| %>
      <div class="row justify-content-center">
        <div class="col-2">
          <%= link_to user_path(user) do %>
           <%= user.name %>さん
          <% end %>
        </div>
        <p class"col-1">投稿数</p>
        <div class="col-2">
          <%= link_to post_user_path(user) do %>
            <%= user.posts.count %>句
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% else %>
    <div class="no-message-box">
       <p class="text-center">まだいません</p>
    </div>
  <% end %>

  <!--ページネーション-->
  <%= render 'layouts/pager', obj: @post %>

</div>

app/views/posts/new.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/errors', obj: @post %>

<div class="container">

  <h2 class="post-title">新規投稿</h2>
  <%= form_with model: @post, url: posts_path, method: :post, local: true do |f| %>
    <!--投稿フォーム-->
    <%= render 'posts/post', f: f %>

    <div class="row form-group justify-content-center">
      <%= f.submit '投稿する', class: "col-2 btn btn-info btn-lg" %>
    </div>
  <% end %>
</div>

app/views/posts/ranking.html.erb
<div class="container">

  <div class="ranking">
    <p class="ranking-message">過去三日間の投稿の中でいいね数が一番多かった投稿を表示しています</p>
  </div>

  <!--今日の一位-->
  <% @today.each do |post| %>
    <div class="day-senryu">
      <h2><i class="fas fa-medal"></i>今日の一句<i class="fas fa-medal"></i></h2>
    </div>
    <!--投稿表示-->
    <div class="row day-box">
      <div class="post">
        <%= render 'posts/item', post: post %>
        <div class="sub">
          <%= render 'posts/time', post: post %>
          <%= render partial: 'posts/favorite', locals: {post: post} %>
          <%= render 'posts/comment', post: post %>
        </div>
      </div>
    </div>
  <% end %>

  <!--昨日の一位-->

  <% @yesterday.each do |post| %>
    <div class="day-senryu">
      <h2><i class="fas fa-medal"></i>昨日の一句<i class="fas fa-medal"></i></h2>
    </div>
    <!--投稿表示-->
    <div class="row day-box">
      <div class="post">
        <%= render 'posts/item', post: post %>
        <div class="sub">
          <%= render 'posts/time', post: post %>
          <%= render partial: 'posts/favorite', locals: {post: post} %>
          <%= render 'posts/comment', post: post %>
        </div>
      </div>
    </div>
  <% end %>

  <!--一昨日の一位-->
  <% @day_before_yesterday.each do |post| %>
    <div class="day-senryu">
      <h2><i class="fas fa-medal"></i>一昨日の一句<i class="fas fa-medal"></i></h2>
    </div>
    <!--投稿表示-->
    <div class="row day-box">
      <div class="post">
        <%= render 'posts/item', post: post %>
        <div class="sub">
          <%= render 'posts/time', post: post %>
          <%= render partial: 'posts/favorite', locals: {post: post} %>
          <%= render 'posts/comment', post: post %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/posts/show.html.erb
<!--エラーメッセージ-->
<%= render 'layouts/errors', obj: @comment %>

<div class="container">
  <!--投稿表示-->
  <div class="row">
    <div class="post">
      <%= render 'posts/item', post: @post %>
      <div class="sub">
        <%= render 'posts/time', post: @post %>
        <%= render 'posts/favorite', post: @post %>
        <%= render 'posts/comment', post: @post %>
        <%= render 'posts/language', score: @score %>
      </div>
    </div>
  </div>

  <!--投稿ユーザーとログインユーザーが同じだったらボタン表示-->
  <% if @post.user_id == current_user.id %>
    <%= link_to '編集する', edit_post_path(@post.id) %>
    <%= link_to '投稿を削除', post_path(@post.id), method: :delete, remote: true, data: {"turbolinks" => false}, "data-confirm" => "本当に削除しますか？" %>
  <% end %>


  <!--コメント投稿、表示フォーム-->
  <div class="comment_new_btn">
    <%= render 'post_comments/post_comment_new', {post: @post, comment: @comment} %>
  </div>

</div>