config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ルートパス(TOPページ)
  root 'homes#top'

  # ユーザールーティング
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'withdrawal' => 'users#withdrawal_show'
      patch 'withdrawal'
      get 'post'
      get 'like'
    end
  end
  resources :posts do
    member do
      get 'like'
    end
    collection do
      get 'ranking'
      get 'comment'
    end
    resources :post_comments, only: [:create, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get '/search' => 'searchs#search', as: 'search'
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_pager.html.erb
<div class="mt-5 mb-5">
  <%= paginate obj %>
</div>

app/views/layouts/_sign_in.html.erb
<!--ログインしている場合-->

<header class="fixed-top">
    <!--ナビゲーションバー-->
    <nav class="navbar">
      <!--ヘッダーのロゴ-->
      <%= link_to root_path do %>
        <%= image_tag "logo.png", class:"navbar-brand" %>
      <% end %>
      <ul class="navbar nav justify-content-end">
        <li class="nav-item"><p><%= current_user.name %>さん</p></li>
        <li class="nav-item"><i class="fas fa-user-cog"><%= link_to 'マイページ', user_path(current_user) %></i></li>&nbsp&nbsp
        <li class="nav-item"><i class="fas fa-sign-out-alt"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></i></li>
      </ul>
    </nav>
    <!--ログイン時のみメニューバー表示-->
    <nav class="navbar nav justify-content-center menu-bar">
      <ul class="nav">
        <li class="menu"><i class="fas fa-indent">&nbsp<%= link_to '投稿一覧', posts_path %></i></li>
        <li class="menu"><i class="fas fa-plus-square">&nbsp<%= link_to '投稿する', new_post_path %></i></li>
        <li class="menu"><i class="fas fa-crown">&nbsp<%= link_to '今日の一句', ranking_posts_path %></i></li>
        <li class="menu"><i class="fas fa-comment-dots">&nbsp<%= link_to 'コメント募集', comment_posts_path %></i></li>
          <!--検索バー-->
          <div class="row justify-content-cemter search">
            <%= form_with url: search_path, method: :get, class: "form-inline", local: true do |f| %>
              <div class="bar">
                <%= f.select :model, [["お題","theme"],["川柳","text"],["投稿ユーザー","user"]], {},  {class: "form-control input-sm"} %>
              </div>
              <div class="bar">
                <%= f.text_field :content, value: params[:content], :placeholder => "Search", class: "form-control input-sm" %>
                <%= f.button :type => "submit", style: 'border-style: none;', class:"btn search-btn" do %>
                  <i class='fas fa-search'></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </ul>
    </nav>
  </header>

  <!--ログインしている時のheaderの高さ指定-->
  <div class="sign_in-box">
  </div>

app/views/layouts/_sign_out.html.erb
<!--ログインしていない場合-->

<header class="fixed-top">
  <!--ナビゲーションバー-->
  <nav class="navbar">
    <!--ヘッダーのロゴ-->
    <%= link_to root_path do %>
      <%= image_tag "logo.png", class:"navbar-brand" %>
    <% end %>
    <ul class="navbar nav justify-content-end">
      <li class="nav-item"><i class="fas fa-sign-in-alt"><%= link_to 'ログイン', new_user_session_path %></i></li>&nbsp&nbsp
      <li class="nav-item"><i class="fas fa-user-plus"><%= link_to '新規登録', new_user_registration_path %></i></li>
    </ul>
  </nav>
</header>

<!--ログインしていない時のheaderの高さ指定-->
<div class="sign_out-box">
</div>
  

app/views/layouts/_success.html.erb
<% if flash[:notice] %>
  <p class="alert alert-info"><%= flash[:notice] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>日々川柳</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <!--ヘッダー-->
    <% if user_signed_in? %>
      <%= render 'layouts/sign_in' %>
    <% else %>
      <%= render 'layouts/sign_out' %>
    <% end %>
    
    <!--エラーメッセージ配置-->
    <% if flash[:alert] %>
      <p class="alert alert-warning"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>

</html>